title: Jack Eadie
markdown: kramdown
theme: minima
header_pages:
  - cv.md
  # - note.md
  # - blog.md
  # - now.md
  # - ideas.md

kramdown:
  math_engine: mathjax

github_username: jeadie
linkedin_username: jack-eadie
